[package]
name = "simple_mf_play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

winit = "0.28.6"

[build-dependencies]

cmake = "0.1.50"
bindgen = "0.65.1"



